### ISSUE TITLE
[gmodserver] Add functions to allow CS:S content mounting

### ISSUE THREAD

**Issue by Scarsz** [dgibbs64/linuxgsm#136]
I would like to add another option line after asking if the server directory is correct to check if the server wants Counter Strike: Source content to be installed as well as the server. I believe the default value should be true as you will rarely if ever see a garrysmod server that does not have CS:S mounted as it's required for popular gamemodes and addons.

Schooling will be overrunning my life again shortly so if anybody else want's to snag this before I get around to it go ahead.

**Comment by dgibbs64** [comment]
Any Garry's mod admins want to have ago at writing this feature?

**Comment by h3o66** [comment]
I would write it, i'll have a look at it in the next few weeks.

**Comment by dgibbs64** [comment]
Awesome. I look forward to the outcome :D

**Comment by dgibbs64** [comment]
@UltimateByte What do you think to this feature? As im not a gmod expert. I did start some cod ebut haven't finished it.

**Comment by UltimateByte** [comment]
I like it, 90℅ of gmod servers need it, either darkrp or prophunt, many main mods need it. 
If you can make it so it's easier to add other game content it's even better !

**Comment by JimTR** [comment]
why not install counter strike source & edit mount.cfg ?

**Comment by UltimateByte** [comment]
I personally made an srcds user that has all the needed content, which comes mainly from LGSM script installations. Then i edited mount.cfg to use that content. Sometimes i make an update of those, like every 6 months, just in case, and that does the trick.

**Comment by JimTR** [comment]
I would guess CSS would need an update in a shorter period than 6 months ... however I may be wrong ..so the script installs gmod ... then has the ability to CSS ... from that the validate function should perhaps check the contents of mount.cfg & update it ..... but to be fair I'm near 60 & have no idea what players expect

**Comment by UltimateByte** [comment]
I never had an issue working like that (with very few update of the content), as gmod mainly uses texture and sound files, that are not updated frequently. I could setup a cronjob to update that, i just didn't do it as it doesn't seem very useful. Would be cool to have a command like gmodserver update-content btw.
For the validate function, good idea, but i think the validate function doesn't touch mount.cfg, otherwise i should have rebuilt it several times ! As some gmod update worked only with a validate command, and never had to rebuild it.
( You're near 60 ? Rly ? You're kind of our dad/grandpa then ! Amazing :D )

**Comment by JimTR** [comment]
yes I am old ... is that an issue ? .. so update/validate Gmod should also update the paths that are defined in mount.cfg ?

**Comment by UltimateByte** [comment]
It's all but an issue, i love knowing that i'm talking with a more experienced person !
Sorry if i didn't explain well : 
I mean update/validate functions won't touch the mount.cfg as it is.
So maybe this will require another function such as ./gmodserver mount-content that will download and add required variables to mount.cfg
Need to define how the user choose what content to add, or if it's a css content only function.
I should have a look at what dgibbs64 did to tell more about it.

**Comment by JimTR** [comment]
but perhaps the script should just validate the mounts when it validates it's self ... else the some content could be out of date ?

**Comment by UltimateByte** [comment]
If that's what you meant i totally agree. It should validate the content when validating gmod, and update it when updating gmod !

**Comment by JimTR** [comment]
Ok we are talking buggy Gmod ... who knows how it works ... but to be fair if you h

**Comment by UltimateByte** [comment]
You can't add css content with the workshop !
That's why this function would be useful.
Update the game according to the mount, that's clever. But in my case it wouldn't work as the mounted content is owned by another user, this to only download it once and share it across multiple servers. It would have to check if the owner of the file is the same as the one running the script.
Maybe an external lgsm settings file would be preferable for this. The discussion is still open.

**Comment by JimTR** [comment]
you miss the point I am saying just update the CSS base content via steam any mods you have I guess you need to maintain ?

**Comment by UltimateByte** [comment]
How else would you update the content than via steamcmd ?
But of you mounted content from another user (eg : my case) you won't be able to update it.
Didn't get the end of your sentence about mods btw, sorry.

**Comment by dgibbs64** [comment]
Should be easy to update the content. Just needs to loop though the various appid and update with gmod. The hard part is allowing the user to customise which content to mount
