### ISSUE TITLE
[ss3server] default config not being applied

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#247]
Reference commend:https://github.com/dgibbs64/linuxgameservers/issues/245#issuecomment-67427408

Server works great now, but I had to make some changes.

I had to add the port to the server startup line.

	# Start Variables

	ip="192.111.155.210"
	port="27015"

	https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/SeriousSam3BFE/help/DedicatedServer_Readme.txt

	fn_parms(){
	parms="+ip ${ip} +port ${port} +logfile ${gamelog} +exec ${servercfgfullpath}"
	}

Only with a different port since I already have something running under that port. Changing the port in the config file didn't appear to do anything. In fact the server doesn't seem to follow anything about the config file. Default config had 12 players, but the server loaded 16. Also my custom server name wasn't picked up. It defaulted to the servers host name.

I have not tried to rename the server config file to dedicatedserver.cfg to see if that fixes the issue. Just so happy to finally be able to host this game on my Linux box now.

**Comment by dgibbs64** [comment]
Im not sure how best to go about this as I dont run a serious sam 3 server myself. I could do with a default config for each game type and the best default parms to set.

I think the ideal parms are as follows as @lblanchardiii specified. But i'm not sure about the configs.
parms="+gamemode ${gamemode} +ip ${ip} +port ${port} +logfile ${gamelog} +exec Content/SeriousSam3/Config/survival.cfg"

If anyone is willing to post some vanilla default configs for each game mode that they know works I will implement them in to the script. Also is survival the main game mode used or is there another one? 

@lblanchardiii you mention that you use absolute path for the config however your example is a relative path. Please can you confirm which is best. Also never use 777 permissions as this is writable to anyone and not best practice (bad things can happen). something like 774 or or 744 may be better. It may be that the server requires write access to the config?

**Comment by Scarsz** [comment]
Should honestly just CHOWN the server's folder if it needs write access imo.

**Comment by lblanchardiii** [comment]
Cooperative is the default gamemode and CooperativeCoinOp is similar to the default one but you don't have to worry about dying as much. Survival is a unique gamemode and not very common. Majority of the servers are Cooperative or one of the Versus modes.

With Cooperative and CooperativeCoinOp you don't really need any special parms unless you are running multiple servers on the same install/IP. Then you'll want to be able to change the ip or port. By default everything just works like it should.

For Survival you'll want to use the local prj_strMapList in the config file otherwise it will just play the same map over and over. By default it's the SV_Canyon map that will be set on repeat.

The permissions at 777 might not be required, but it was something I set them to for testing purposes. I never went back to check if it was required or not.

Absolute path is not required as I originally thought.

One thing for sure is though I don't have any "commented out" lines in my config files as that seemed to cause issues with the game engine loading it.

**Comment by dgibbs64** [comment]
Cheers @lblanchardiii I will run though your comment fully and come up with somthing.

**Comment by dgibbs64** [comment]
I have adjusted the game type and added a link in for the SS3 Server GUI 3 tool.
https://github.com/dgibbs64/linuxgsm/commit/4cb78a3ef9ef147815235929841cd57a94bd919c
