### ISSUE TITLE
[LGSM] Migrate gsquery.py in to functions

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#567]
This should be in functions now and will also remove it being an optional feature as I dont believe it needs to be optional any more.

**Comment by dgibbs64** [comment]
as per issue #299 python-valve may be a good replacement for gsquery.py for source based servers.

**Comment by UltimateByte** [comment]
OK, so one idea i had today, would allow to check if an SRCDS server is down another way than pinging it. Because sometime it's not usable, but still responds to ping. My way doesn't require to implement RCON !

On a failed server that still reponds to serverquery, type : 

`stats`

-> It returns nothing. So the check would be : Does inputting "stats" writes anything relevant into the console ? If not, restart the server.
Not sure how to check that, using the console log would be fine i think. BTW, that's one more way to integrate that into functions and to make sure a server didn't freeze.

**Comment by dgibbs64** [comment]
I am closing this and sticking with gsquery.py for now as works well. If anyone comes up with an improved method for querying servers or using rcon then an issue should be raised
