### ISSUE TITLE
Garry's Mod -disableluarefresh

### ISSUE THREAD

**Issue by Herover** [dgibbs64/linuxgsm#590]
In Garry's Mod theres a launch parameter to stop refreshing lua files when changed, -disableluarefresh.

Of course it's possible to just append -disableluarefresh manually but it would be convenient to have a easy enable/disable setting in lgsm too.

Thanks.

**Comment by dgibbs64** [comment]
I don't think this would be a good idea. As there are likely many parms for garrys mod I tend to only have common parms in there own variable such as map and ports. Server specific parms I don't add. It is up to the server admin to customize the parms as they see fit. Over-wise I would end up with a massive list of possible options for users to add

**Comment by UltimateByte** [comment]
Yep, gamemode whis is very used was already added if i remind well, that's already enough in my opinion for common start options.

**Comment by jaredballou** [comment]
This is where the "srcds_params" variable in my external configs thing comes into play. I had similar issues with Insurgency and its weird commands, it might be worth plotting out how to add parameters properly for all the games. For example, in Insurgency (and srcds in general) the order can be important, my hacky way to get around it was to put the extra parameter variable between the - and + parameters and require the server admins to enter commands in the right order there. Some games may require different variables to be injected at different points. But unless Insurgency is a snowflake, this seems like an idea we may want to look into a bit more.

**Comment by UltimateByte** [comment]
Yep. Maybe your variable could be useful to integrate in main game scripts @jaredballou 

That thing appart, i'm personally happy that gmod linux server finally supports lua auto refresh... Will make my life easier when setting up back some DarkRPs...

**Comment by Herover** [comment]
Having a params variable could be nice as a alternative :)

@UltimateByte it should be noted that it's generally best-practice to have it disabled on production servers since it's easy to break stuff with it too.

**Comment by UltimateByte** [comment]
Yep, one missing character, then you gotta restart the server :p 
BTW i really don't think such a command will be added natively, otherwise, the script would support all commands in an advanced start options category, but it sounds like it's too much.

You can still make your own custom command pretty easilly as jaredballou did.
I think it would be a good idea to get this a default standard to all game servers.

Add this variable somewhere and put your additional commands in it: 
additional_parms=""

Then change
fn_parms(){
parms="-game garrysmod -strictportbind -ip ${ip} -port ${port} +host_workshop_collection ${workshopcollectionid} -authkey ${workshopauth} +clientport ${clientport} +tv_port ${sourcetvport} +gamemode ${gamemode} +map ${defaultmap} +sv_setsteamaccount ${gslt} +servercfgfile ${servercfg} -maxplayers ${maxplayers}"
}

to : 
fn_parms(){
parms="-game garrysmod -strictportbind -ip ${ip} -port ${port} +host_workshop_collection ${workshopcollectionid} -authkey ${workshopauth} +clientport ${clientport} +tv_port ${sourcetvport} +gamemode ${gamemode} +map ${defaultmap} +sv_setsteamaccount ${gslt} +servercfgfile ${servercfg} -maxplayers ${maxplayers} ${additional_parms}"
}

**Comment by UltimateByte** [comment]
I hope it helped. Closing for now but feel free to re-open if needed.
Have a nice admin time !
