### ISSUE TITLE
[cs:go] older version ?  can not connect to local server

### ISSUE THREAD

**Issue by bisam** [dgibbs64/linuxgsm#643]
Hi again,

this time I cannot connect to my LAN only cs:go server. -_- I started it with the default configuration, added no token, because I only want to play locally, and after some unsuccessfull connections I added `sv_lan = 1` to `serverfiles/csgo/cfg/csgo-server.cfg`.

I am trying to connect via console by simply typing: connect "myip"
The error message I get (on the client side) is: 
```"Server is running an older version, client version 13519, server version 2112"```

I am a bit confused by these numbers^^
my server build ID is up-to-date: 
```
No update available:
	Current version: 940396
	Available version: 940396
	https://steamdb.info/app/740/
```
which matches the build number on the URL.

Script details says: csgoserver version:  271215

what am i missing?

**Comment by UltimateByte** [comment]
Sometimes updates don't work properly (steamcmd bug), it displays the new version, while it's still at the old version. To fix that, you have to run the validate command on your server. Try that, then try to connect again.
"Script details says: csgoserver version: 271215" > This is the lgsm script version, don't get confused about that.

Protip : connect "yourip" without a port only works because you're using the default 27015 port, but if you change the port, you'll have to specify the port : connect 192.168.x.x:2701x

**Comment by bisam** [comment]
hm, i already tried to validate it, it downloaded the steamcmd again and nothing changed :/

**Comment by UltimateByte** [comment]
Weird. I don't get why it would show "version 2112" while the actual version is 940396 in the first place...  Probably steam usual crap.
I had a csgo server installed that wasn't running for a while, that i didn't update since the last update. Updating it did nothing except update steamcmd, but validating it updated a whole bunch of files. 
I've been able to connect successfully after that.
Just to know, what is your distro ?

**Comment by UltimateByte** [comment]
As it's quite certainly a non-script issue, I'd suggest to close this and go to the general support if you're OK.
https://steamcommunity.com/groups/linuxgsm/discussions
You'd probably have more chances to get help from other experienced admins of steam games about this very specific issue.
Link to this git issue anyway on the thread you will create.

**Comment by bisam** [comment]
Just for documentation: The problem were the default ports. Insurgency and cs:go use the same default port, and I had an Insurgency server running on the same machine.

All I had to do was change the default port on one of the servers and everything worked :D
