### ISSUE TITLE
[Question] CS:GO What is mapgroup/steamuser/steampass for?

### ISSUE THREAD

**Issue by FrozenBeard** [dgibbs64/linuxgsm#690]
Im trying to figure out how to Cycle through my Maps in CS:GO from a selection of workshop maps I have added to my CS:GO server, now I see a ton of different files that may be able to do this in my /cfg folder, but I also see mapgroup in the main csgoserver file, what is this referencing? Why is the entire file not documented?

**Comment by UltimateByte** [comment]
Ignore steamuser/steampass, not used for CS GO.
The only thing you need to worry in CSGO is the GSLT : https://github.com/dgibbs64/linuxgsm/wiki/Game-Server-Login-Token

If you need info about the workshop, i documented it
https://github.com/dgibbs64/linuxgsm/wiki/Workshop

Concerning the gamecycle, you should search in valve's CSGO server documentation. It's specific to CSGO, not to LGSM.
LGSM provides you an easy way to setup map and mapgroup at the start of your server. And this is what you should use to setup that at the start of your server, not the /cfg folder, unless you have specific configs for specific gamemodes, that you wish to change on the fly, but start option will help you starting with the default mode that you wish.

**Comment by UltimateByte** [comment]
Closing for now, hope i helped you figuring this out.
If you need help with non script issue, please post here : https://steamcommunity.com/groups/linuxgsm/discussions

Feel free to re-open this issue if needed.
Have a good one !

**Comment by FrozenBeard** [comment]
Thanks for the information @UltimateByte Its been about 10 years since I hosted a CS server, I noticed that sourcemod is still going! Since im sure you could give me a straight answer, Would I be better off managing my files Via sourcemod?

**Comment by UltimateByte** [comment]
Sourcemod is the best admin plugin you'll find for TF/CSGO/CSS, and about all source games of that kind.
What do you mean "managing my files via SM" ? Sourcemod isn't a file manager of any kind.

**Comment by FrozenBeard** [comment]
@UltimateByte Map cycle files etc, it seems as though SM uses its own set of files for changing maps and game settings?

**Comment by UltimateByte** [comment]
I believe SM uses mapcycle.txt anyways. I'm not an expert with CS servers, i only have 2 CSS servers i modded a while ago, i remember it was painful to get the gungame working well... and one blank CSGO server...
I know you can get interesting things for map voting and map cycle with sourcemod
https://wiki.alliedmods.net/Map_Management_Plugins_(SourceMod)

I'd advise you to check sourcemod wikis and forums, they have your answers more than i or anyone on this github do.
Otherwise, once again, general help is given here : https://steamcommunity.com/groups/linuxgsm/discussions
