### ISSUE TITLE
Teeworlds Install is not working (No subscription)

### ISSUE THREAD

**Issue by redrum181** [dgibbs64/linuxgsm#701]
Hello all,

im trying to install the Teeworlds server with your script but it dont works. I have setup a special steam account for it.

Logging in user '443562server' to Steam Public...Logged in OK
Waiting for license info...OK
ERROR! Failed to install app '380840' (No subscription)

Any idea? Maybe the server got removed from steam because i cant find it on the steam page?

Best

**Comment by UltimateByte** [comment]
Hi there. No subscription error means the steam account doesn't own the game. You need to buy it for that account.

**Comment by redrum181** [comment]
Correct me if im wrong but is Teeworlds not for free?

**Comment by dgibbs64** [comment]
You are right TeeWorlds is free

**Comment by UltimateByte** [comment]
I'm not sure why you get as "no subscription" error then, as it only occurs for either game servers that require logging-in to a steam account, or games that need to be owned. As you said you setup a steam account for that purpose, i assume you put it in your script config.

Does this account own at least one game ? Because i know a blank account can't add friends. This may be another limitation : A blank account my not allow you to run a server that needs a steam account.

**Comment by UltimateByte** [comment]
OK, i just tried : I had to install the game onto my steam account to get rid of that "no subscription" error. Even if it's free. Try it out.
If it's not enough, then you may need to actually buy at least one game on that account.
Keep us tuned.

**Comment by UltimateByte** [comment]
If you need more help, please post to the general support which is here : http://steamcommunity.com/groups/linuxgsm/discussions/

However, if you find a bug or a feature request related to this issue, feel free to re-open it.
