### ISSUE TITLE
CSGO and Sourcemod

### ISSUE THREAD

**Issue by jaccovdwijgaart** [dgibbs64/linuxgsm#785]
So I am running LGSM on Ubuntu x64 14.4.4 LTS Server and it is working fine but I can't get sourcemod and metamod to work. I have unzipt the files downloaded from the source and metamod website (just like Windows) but after starting the server it doesn't seem to work.

Am I missing something? I am switching all my servers from Windows to linux and I am not used to the operation system at all.

**Comment by jaccovdwijgaart** [comment]
-I am running CS:GO servers, I need help fast, thank you! :)

**Comment by kurdt94** [comment]
I got this stuff working on my server. Found a tutorial on youtube i believe, be sure the right folder structure is used.

**Comment by UltimateByte** [comment]
Yep, it's quite easy. Also make sure you got the linux version (if i remember well, there is a windows and a linux version).
Folder structure, not that hard : http://image.noelshack.com/fichiers/2016/16/1461237608-css.png

Github is preferably for bug report btw. Otherwise, please use the steam group. http://steamcommunity.com/groups/linuxgsm/discussions/0/

**Comment by UltimateByte** [comment]
Issue opened here, closing. http://steamcommunity.com/groups/linuxgsm/discussions/0/364039531223669578/

**Comment by jaccovdwijgaart** [comment]
Yes, thank you for the comments! Have a nice day guys! :)
