### ISSUE TITLE
[ARK] Restart script issue.

### ISSUE THREAD

**Issue by TOXid** [dgibbs64/linuxgsm#806]
Restart script does not pause between Stop and Start function, so server does not have time to release ports and  result of execute Restart function is `CreateBoundSocket: ::bind couldn't find an open port between 27015 and 27015`.

**Comment by cedarlug** [comment]
I have a working fix for this ready for a pull but would like a second/third set of eyes on the actual crux of the issue (rather than just a fix for it).

Can someone confirm:

- Changing "<tt>QueryPort=</tt>" in <tt>serverfiles/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini</tt> has no effect on the actual port used in the game.  None.  Changing this to anything other than 27015 and starting the server has no effect. This is problematic because <tt>./arkserver details</tt> - <tt>info_config.sh</tt> specifically - pulls this (incorrect) information to report the ports used.
- When issuing "<tt>./arkserver stop</tt>", a rogue <tt>ShooterGame</tt> process is left bound on both "<tt>Port</tt>+1" and "<tt>QueryPort</tt>".
- This process does not exit gracefully within a reasonable amount of time.

ADV<b>thanks</b>ANCE

**Comment by dgibbs64** [comment]
Please put the request in to the development branch when you are ready :+1:

**Comment by cedarlug** [comment]
#820 posted

**Comment by dgibbs64** [comment]
Has this been fully resolved with https://github.com/dgibbs64/linuxgsm/pull/828 ? If so this can be closed. I have merged the ARK fix in to master now

**Comment by cedarlug** [comment]
Yes  - merged with master #828 closes this
