### ISSUE TITLE
Add python as a require dependency

### ISSUE THREAD

**Issue by dgibbs64** [dgibbs64/linuxgsm#869]
Along with column

**Comment by AlexCSilva** [comment]
not all linux distros come with python?

**Comment by hrombach** [comment]
Some versions of Arch Linux for example. :)

**Comment by dgibbs64** [comment]
Yup found this out today. Specifically having some issues with minimal installs of Ubuntu for example. Having the same issue with the column command as well :/. Many users don't seem to understand the "command not found" error and regularly post asking what the issue is.

**Comment by dgibbs64** [comment]
On another note LGSM does not official support Arch however i think it would be great if an Arch user was willing to do some development for LGSM to test and make sure it all works and also add a function for arch dependency checks

**Comment by AlexCSilva** [comment]
I've used manjaro which is based on arch, I think the commands are the same

**Comment by hrombach** [comment]
The main differences I can think of are pacman and the fact that in most Arch installations the default shell is zsh instead of bash which can have compatibility issues with things like globbing patterns. In my case bash wasn't even installed initially. I could give it some tests, currently I'm using LGSM on a Debian server but if I find the time I could try and see how it does on Arch. :)

**Comment by dgibbs64** [comment]
I have completed this task. Hopfully you get the chance to setup an arch checker.
