### ISSUE TITLE
Arma 3 Server Start Fail!

### ISSUE THREAD

**Issue by SlowMotion16** [dgibbs64/linuxgsm#906]
![kk](https://cloud.githubusercontent.com/assets/20205420/16450449/49efbe58-3dfd-11e6-8097-542540337ab0.png)

I need Help0?!

**Comment by UltimateByte** [comment]
`./arma3server details`

**Comment by SlowMotion16** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/20205420/16451104/24b734be-3e01-11e6-8634-cae65dcda085.png)

**Comment by UltimateByte** [comment]
Your kernel is pretty damn outdated. Weird.
Not sure if this is related.
Tmux seems not to be able to get the start parameters correctly.
Did you try `./arma3server debug` ? Was it your first screenshot already ?

**Comment by SlowMotion16** [comment]
How do I update it

**Comment by UltimateByte** [comment]
What's your server provider ?
Do you have anything else installed on your server ?

**Comment by cedarlug** [comment]
Regarding the kernel: Based on the kernel version, the server is an openVZ container running on a Proxmox server specially designed for virtualization. Proxmox runs a tailored RedHat kernel which is up to date, even though it's a 2.6 kernel.

So...based on the inability to connect to the service running on your local host, knowing your network settings would be immensely helpful - the output of the suggested netstat command (please post to pastebin and not post a screenshot) as well as the output of "/sbin/ifconfig -a"

Since you're running within an OpenVZ container, you might have virtualization limits in place from your provider as well.  Start with the two outputs requested above (posted to pastebin, not a screenshot).

**Comment by cedarlug** [comment]
You can also try to remove tmux from the equation.  What happens when you just run:

`./arma3server debug`

**Comment by berserkerX86** [comment]
I just had the same problem on CentOS but it went away after ./arma3server debug.

**Comment by cedarlug** [comment]
@berserkerX86, @SlowMotion16: posting your log/console/arma3-server-console.log would be helpful.

**Comment by cedarlug** [comment]
close?
