### ISSUE TITLE
permission issues found  gmod server

### ISSUE THREAD

**Issue by pab14567** [dgibbs64/linuxgsm#939]
So ive created everything, i've uploaded everything and whenever i try to start the gmod server, under the garrysmod username, it keeps saying perrmission denied. User does not have access to filse () then it shows every file in garrysmod.  This happened after i started server once and stopped it and a tutorial said to put sv.db and data folder to 755

**Comment by UltimateByte** [comment]
Protip if you did crap with permissions : 
`chown -R * username:username`
Google about chown if needed.

**Comment by pab14567** [comment]
Thank you so much, I'm sorry to waste your time, about this.

**Comment by UltimateByte** [comment]
No problem about it. If i had no time at all i wouldn't answer. :p 
You'd rather be sorry to use github instead of the steam group for this kind of issue ! :p

**Comment by pab14567** [comment]
wait, what is this supposed to do ? 
chown -R * username:username

and what am i supposed to do ?

**Comment by dgibbs64** [comment]
man chown
chown - change file owner and group

change owner and group recursively e.g

    chown -R * username:group

    chown -R /home/csgoserver csgoserver:csgoserver

**Comment by pab14567** [comment]
For the username:group do I put the main core username and the garrysmod group like root:garrysmod?

or do i leave it as it is, and same with the csgoserver part, do i just put gmodserver on both parts?Sorry, I'm kinda new to this

**Comment by UltimateByte** [comment]
Any user has a group crated with it. In your case, you cant files to belong to your user and group. Certainly not to root.

Does it answer your question ?

**Comment by pab14567** [comment]
This all happened after a tutorial said to put sv.db and and data folder to 755.

**Comment by UltimateByte** [comment]
Then sv.db should have been the only file affected.
By the way, sv.db is not something you'd like to share or take from elsewere, it contains a lot (if not every in some cases) of data from your personal gmod server. So hopefully you just put a backup or your old sv.db or you could get rekt.

**Comment by pab14567** [comment]
Yeah, I know about the data, in it 

here's the link to the tutorial that said to change the file permissions to 755

**Comment by pab14567** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=555696186

**Comment by UltimateByte** [comment]
When a tutorial advises a VPS for a game server, run away. lol

"If your server is going to be for around 42-64 people then I recommend going with:
2 high spec intel xeon V-Core (3.2GHz +)"
Lol, 2 CPU for a monothreaded process.

"you may notice that nothing saves (if you have already launched the server). This is because of permissions, so what you need to do is use the SFTP program to edit the permissions of the data folder and sv.db file to 755"
> This is complete bullshit.

However, if your FTP program is correctly set, changing permissions won't affect ownership.

Didn't read a lot from this tutorial, but it seems like it contains a lot of bullshit. I wouldn't learn from that.

For linux system admin, search better tutorials. For Instructions about LGSM, they are given on gameservermanagers.com's game page, and we got a pretty well ellaborated wiki here to learn the basics and go further : https://github.com/dgibbs64/linuxgsm/wiki
For gmod specific stuff, such as mounting css content to your server, then you can use LGSM too, just make another user, i usually do an "srcds" user with a subfolder by game content i wanna mount. Then you just edit mount.cfg accordingly. Pretty straight forward.
To conclude, there is not any point where you gotta change chmod or chown if you do things properly.

**Comment by pab14567** [comment]
So basically, cause im fucked now, i just re-install everything, i just delete all those files, or re-install the vps ?

**Comment by UltimateByte** [comment]
Just login as root and apply the chown command we told several times. Permissions issue will disappear.

**Comment by UltimateByte** [comment]
Anyways, in order to be a good admin, i'd suggest to get some Linux knowlege, try stuff, fuckup and reinstall a test machine, before getting into something more serious.

**Comment by pab14567** [comment]
Im still a bit confused on  the chown commands. Do i just copy paste?  the new username i created for the gmod server is called garrysmod, so do i just replace

chown -R /home/gmodserver gmodserver:gmodserver

with  chown -R /home/garrysmod  garrysmod:garrysmod?

**Comment by UltimateByte** [comment]
That's it. ;)

**Comment by UltimateByte** [comment]
This is one of the very basics of Linux, that's cool you learned it, but you should already know that if you plan making servers. As i said, really consider experimenting and learning a bit more before starting something serious. You don't need months, you just need to try a lot of stuff quite a few times.

I guess we can close the issue. Please, use the Steam Group if you got more questions, I and others will be glad to help as long as you're kind, clear, and provide enough information for us to help you. 
http://steamcommunity.com/groups/linuxgsm/discussions/0/
And always remember that google is your best friend !

Have a great Linux time ;)
